DROP VIEW IF EXISTS MIG_META.VW_MIG_DAG_TBL_MPG;
DROP VIEW IF EXISTS MIG_META.VW_MIG_RUN_SUM;
DROP VIEW IF EXISTS MIG_META.VW_MIG_DAG_RUN_SUM;

DROP TABLE IF EXISTS MIG_META.TB_MIG_VALD_COL_RSLT;
DROP TABLE IF EXISTS MIG_META.TB_MIG_VALD_RSLT;
DROP TABLE IF EXISTS MIG_META.TB_MIG_RUN_LOG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_DAG_RUN;
DROP TABLE IF EXISTS MIG_META.TB_MIG_S3_MANF;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_LOAD_HIST;
DROP TABLE IF EXISTS MIG_META.TB_MIG_MPG_CHG_HIST;
DROP TABLE IF EXISTS MIG_META.TB_MIG_COL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SRC_LAYOUT;
DROP TABLE IF EXISTS MIG_META.TB_MIG_CONN;
DROP TABLE IF EXISTS MIG_META.TB_MIG_ARTF_ITEM;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_DEP;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_DAG_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_DEP;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_AREA;

CREATE TABLE MIG_META.TB_MIG_CONN (
    CONN_ID VARCHAR(100) NOT NULL,
    CONN_NM VARCHAR(200) NOT NULL,
    DBMS_CD VARCHAR(30) NOT NULL,
    CHAR_LEN_MUL INTEGER NOT NULL DEFAULT 1,
    S3_STG_PATH VARCHAR(1000),
    SEC_SECT_NM VARCHAR(100) NOT NULL,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (CONN_ID)
);

CREATE TABLE MIG_META.TB_MIG_SBJ_AREA (
    SBJ_AREA_CD VARCHAR(20) NOT NULL,
    SBJ_AREA_NM VARCHAR(200),
    UP_SBJ_AREA_CD VARCHAR(20),
    DISP_ORD INTEGER NOT NULL DEFAULT 0,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (SBJ_AREA_CD)
);

CREATE TABLE MIG_META.TB_MIG_SBJ_DAG_MPG (
    SBJ_AREA_CD VARCHAR(20) NOT NULL,
    DAG_DVSN_CD VARCHAR(30) NOT NULL,
    DFLT_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    MAX_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    SCHD_CD VARCHAR(30) NOT NULL DEFAULT 'NONE',
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (SBJ_AREA_CD, DAG_DVSN_CD)
);

CREATE TABLE MIG_META.TB_MIG_SRC_LAYOUT (
    SRC_LAYOUT_ID BIGINT IDENTITY(1,1) NOT NULL,
    SRC_CONN_ID VARCHAR(100) NOT NULL,
    STD_DT VARCHAR(8) NOT NULL,
    SRC_SCH_NM VARCHAR(128) NOT NULL,
    SRC_TBL_NM VARCHAR(128) NOT NULL,
    SRC_TBL_CMT VARCHAR(1000),
    SRC_COL_NO INTEGER NOT NULL,
    SRC_COL_NM VARCHAR(128) NOT NULL,
    SRC_COL_CMT VARCHAR(1000),
    SRC_DATA_TYPE VARCHAR(200) NOT NULL,
    SRC_DATA_LEN VARCHAR(100),
    SRC_PK_YN BOOLEAN NOT NULL DEFAULT FALSE,
    SRC_NULL_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (SRC_LAYOUT_ID)
);

CREATE TABLE MIG_META.TB_MIG_TBL_MPG (
    MPG_ID BIGINT IDENTITY(1,1) NOT NULL,
    PRJ_CD VARCHAR(100) NOT NULL,
    SBJ_AREA_CD VARCHAR(20) NOT NULL,
    SRC_CONN_ID VARCHAR(100) NOT NULL,
    SRC_SCH_NM VARCHAR(128) NOT NULL,
    SRC_TBL_NM VARCHAR(128) NOT NULL,
    TGT_CONN_ID VARCHAR(100) NOT NULL,
    TGT_SCH_NM VARCHAR(128) NOT NULL,
    TGT_TBL_NM VARCHAR(128) NOT NULL,
    TGT_TBL_CMT VARCHAR(2000),
    LOAD_STS_CD VARCHAR(10) NOT NULL DEFAULT 'FULL',
    SYS_COL_NM_ARR VARCHAR(65535),
    SYS_COL_FMT_CD VARCHAR(30),
    INCR_MTHD_CD VARCHAR(20),
    SRC_INCR_COL_NM_ARR VARCHAR(65535),
    PARL_MTHD_CD VARCHAR(10) NOT NULL DEFAULT 'NONE',
    PARL_CND_ARR VARCHAR(65535),
    TGT_DDL_SQL VARCHAR(65535),
    META_VER_NO INTEGER NOT NULL DEFAULT 1,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MPG_ID)
);

CREATE TABLE MIG_META.TB_MIG_COL_MPG (
    COL_MPG_ID BIGINT IDENTITY(1,1) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    COL_ORD INTEGER NOT NULL,
    SRC_COL_NO INTEGER,
    SRC_COL_NM VARCHAR(128),
    SRC_DATA_TYPE VARCHAR(200),
    SRC_NULL_YN BOOLEAN,
    SRC_KEY_ROLE_CD VARCHAR(20),
    TGT_COL_NO INTEGER,
    TGT_COL_NM VARCHAR(128) NOT NULL,
    TGT_COL_CMT VARCHAR(2000),
    TGT_DATA_TYPE VARCHAR(200) NOT NULL,
    TGT_NULL_YN BOOLEAN NOT NULL DEFAULT TRUE,
    TGT_KEY_ROLE_CD VARCHAR(20),
    TRNSF_EXPR VARCHAR(65535),
    DFLT_EXPR VARCHAR(65535),
    SUM_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    HSH_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (COL_MPG_ID)
);

CREATE TABLE MIG_META.TB_MIG_MPG_CHG_HIST (
    MPG_CHG_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    META_VER_NO INTEGER NOT NULL,
    CHG_DVSN_CD VARCHAR(20) NOT NULL,
    CHG_RSN VARCHAR(1000) NOT NULL,
    BF_VAL VARCHAR(65535),
    AF_VAL VARCHAR(65535),
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MPG_CHG_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_S3_MANF (
    S3_MANF_ID BIGINT IDENTITY(1,1) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    PARL_SEQ INTEGER NOT NULL DEFAULT 1,
    SRC_WHERE_CND VARCHAR(65535),
    LOAD_MTHD_CD VARCHAR(10) NOT NULL,
    S3_MNF_PATH VARCHAR(2000) NOT NULL,
    S3_DATA_PATH VARCHAR(2000) NOT NULL,
    FILE_FMT_CD VARCHAR(20) NOT NULL DEFAULT 'PARQUET',
    SRC_ROW_CNT BIGINT,
    S3_ROW_CNT BIGINT,
    S3_BYTE_SIZE BIGINT,
    VALD_STS_CD VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    INS_STS_CD VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (S3_MANF_ID)
);

CREATE TABLE MIG_META.TB_MIG_DAG_RUN (
    DAG_EXEC_ID BIGINT IDENTITY(1,1) NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    DAG_DVSN_CD VARCHAR(30) NOT NULL,
    MAP_CNT INTEGER NOT NULL DEFAULT 0,
    SUC_CNT INTEGER NOT NULL DEFAULT 0,
    RUN_CNT INTEGER NOT NULL DEFAULT 0,
    ERR_CNT INTEGER NOT NULL DEFAULT 0,
    WRK_STS_CD VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    WRK_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    WRK_END_DTM TIMESTAMP,
    WRK_ELPS_SEC BIGINT,
    WRK_MSG VARCHAR(4000),
    PRIMARY KEY (DAG_EXEC_ID)
);

CREATE TABLE MIG_META.TB_MIG_RUN_LOG (
    RUN_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    MPG_ID BIGINT,
    TASK_NM VARCHAR(250) NOT NULL,
    WRK_DVSN_CD VARCHAR(20) NOT NULL,
    LOAD_MTHD_CD VARCHAR(10),
    WRK_STS_CD VARCHAR(20) NOT NULL,
    SRC_ROW_CNT BIGINT,
    TGT_ROW_CNT BIGINT,
    S3_BYTE_SIZE BIGINT,
    S3_MNF_PATH VARCHAR(2000),
    SQL_FILE_PATH VARCHAR(2000),
    SRC_WHERE_CND VARCHAR(65535),
    WRK_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    WRK_END_DTM TIMESTAMP,
    WRK_ELPS_SEC BIGINT,
    WRK_MSG VARCHAR(4000),
    PRIMARY KEY (RUN_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_VALD_RSLT (
    VALD_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    VALD_DVSN_CD VARCHAR(20) NOT NULL,
    S3_MANF_PATH VARCHAR(2000),
    CNT_VALD_STS_CD VARCHAR(20) NOT NULL,
    SRC_CNT BIGINT,
    TGT_CNT BIGINT,
    CNT_DIFF BIGINT,
    SUM_VALD_STS_CD VARCHAR(20),
    HSH_VALD_STS_CD VARCHAR(20),
    VALD_STS_CD VARCHAR(20) NOT NULL,
    VALD_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    VALD_END_DTM TIMESTAMP,
    VALD_ELPS_SEC BIGINT,
    VALD_MSG VARCHAR(4000),
    PRIMARY KEY (VALD_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_VALD_COL_RSLT (
    VALD_COL_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    VALD_HIST_ID BIGINT NOT NULL,
    VALD_ITEM_CD VARCHAR(20) NOT NULL,
    COL_NM VARCHAR(128),
    SRC_VAL VARCHAR(4000),
    TGT_VAL VARCHAR(4000),
    DIFF_VAL VARCHAR(4000),
    VALD_STS_CD VARCHAR(20) NOT NULL,
    PRIMARY KEY (VALD_COL_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_TBL_LOAD_HIST (
    LOAD_HIST_ID BIGINT IDENTITY(1,1) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    BF_LOAD_STS_CD VARCHAR(10) NOT NULL,
    AF_LOAD_STS_CD VARCHAR(10) NOT NULL,
    CHG_RSN VARCHAR(1000) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (LOAD_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_ARTF_ITEM (
    ARTF_DVSN_CD VARCHAR(30) NOT NULL,
    ITEM_ID VARCHAR(100) NOT NULL,
    ITEM_NM VARCHAR(200) NOT NULL,
    DISP_ORD INTEGER NOT NULL,
    OUT_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ARTF_DVSN_CD, ITEM_ID)
);

COMMENT ON TABLE MIG_META.TB_MIG_CONN IS '이관접속정보';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_ID IS '접속식별자';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_NM IS '접속명';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.DBMS_CD IS 'DBMS코드';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CHAR_LEN_MUL IS '문자길이배수';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.S3_STG_PATH IS 'S3기준경로';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.SEC_SECT_NM IS 'Secrets섹션명';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_AREA IS '이관주제영역';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_NM IS '주제영역명';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.UP_SBJ_AREA_CD IS '상위주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.DISP_ORD IS '표시순서';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_DAG_MPG IS '주제영역DAG설정';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DAG_DVSN_CD IS 'DAG구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DFLT_PARL_CNT IS '기본병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.MAX_PARL_CNT IS '최대병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.SCHD_CD IS '일정코드';
COMMENT ON TABLE MIG_META.TB_MIG_SRC_LAYOUT IS '원천레이아웃이력';
COMMENT ON COLUMN MIG_META.TB_MIG_SRC_LAYOUT.STD_DT IS '기준일자';
COMMENT ON COLUMN MIG_META.TB_MIG_SRC_LAYOUT.SRC_CONN_ID IS '원천접속식별자';
COMMENT ON TABLE MIG_META.TB_MIG_TBL_MPG IS '원천대상테이블매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PRJ_CD IS '프로젝트코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.LOAD_STS_CD IS '기본적재상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SYS_COL_NM_ARR IS '시스템컬럼명배열';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SYS_COL_FMT_CD IS '시스템컬럼데이터형식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.INCR_MTHD_CD IS '증분방식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SRC_INCR_COL_NM_ARR IS '원천증분컬럼명배열';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_TBL_CMT IS '대상테이블설명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PARL_MTHD_CD IS 'S3추출병렬방식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PARL_CND_ARR IS 'S3추출병렬조건배열';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_DDL_SQL IS '대상DDL문';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.META_VER_NO IS '메타버전번호';
COMMENT ON TABLE MIG_META.TB_MIG_COL_MPG IS '원천대상컬럼매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_COL_CMT IS '대상컬럼설명';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TRNSF_EXPR IS '변환SQL식';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SUM_VALD_YN IS '합계검증여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.HSH_VALD_YN IS '해시검증여부';
COMMENT ON TABLE MIG_META.TB_MIG_MPG_CHG_HIST IS '매핑변경이력';
COMMENT ON COLUMN MIG_META.TB_MIG_MPG_CHG_HIST.CHG_DVSN_CD IS '변경구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_MPG_CHG_HIST.CHG_RSN IS '변경사유';
COMMENT ON TABLE MIG_META.TB_MIG_S3_MANF IS 'S3기준본매니페스트';
COMMENT ON COLUMN MIG_META.TB_MIG_S3_MANF.LOAD_MTHD_CD IS '적재방식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_S3_MANF.PARL_SEQ IS '병렬분할순번';
COMMENT ON COLUMN MIG_META.TB_MIG_S3_MANF.SRC_WHERE_CND IS '원천조회조건';
COMMENT ON TABLE MIG_META.TB_MIG_DAG_RUN IS 'DAG실행집계';
COMMENT ON COLUMN MIG_META.TB_MIG_DAG_RUN.DAG_DVSN_CD IS 'DAG구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_DAG_RUN.MAP_CNT IS '대상테이블건수';
COMMENT ON COLUMN MIG_META.TB_MIG_DAG_RUN.SUC_CNT IS '성공테이블건수';
COMMENT ON COLUMN MIG_META.TB_MIG_DAG_RUN.RUN_CNT IS '진행테이블건수';
COMMENT ON COLUMN MIG_META.TB_MIG_DAG_RUN.ERR_CNT IS '오류테이블건수';
COMMENT ON TABLE MIG_META.TB_MIG_RUN_LOG IS '이관작업로그';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_DVSN_CD IS '작업구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_STS_CD IS '작업상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.SRC_WHERE_CND IS '원천조회조건';
COMMENT ON TABLE MIG_META.TB_MIG_VALD_RSLT IS '이관검증결과';
COMMENT ON COLUMN MIG_META.TB_MIG_VALD_RSLT.VALD_DVSN_CD IS '검증구분코드';
COMMENT ON TABLE MIG_META.TB_MIG_ARTF_ITEM IS '산출물항목정의';

INSERT INTO MIG_META.TB_MIG_CONN (CONN_ID, CONN_NM, DBMS_CD, CHAR_LEN_MUL, S3_STG_PATH, SEC_SECT_NM)
VALUES
    ('SRC_GP', 'Greenplum 원천', 'GREENPLUM', 3, NULL, 'src_gp'),
    ('TGT_RED', 'Redshift 대상', 'REDSHIFT', 3, NULL, 'tgt_red');

CREATE VIEW MIG_META.VW_MIG_DAG_TBL_MPG AS
SELECT T.MPG_ID, T.PRJ_CD, T.SBJ_AREA_CD, T.SRC_CONN_ID, T.SRC_SCH_NM, T.SRC_TBL_NM,
       T.TGT_CONN_ID, T.TGT_SCH_NM, T.TGT_TBL_NM, T.LOAD_STS_CD,
       T.SYS_COL_NM_ARR, T.SYS_COL_FMT_CD, T.INCR_MTHD_CD, T.SRC_INCR_COL_NM_ARR, T.PARL_MTHD_CD, T.PARL_CND_ARR,
       T.TGT_DDL_SQL, T.META_VER_NO, S.S3_STG_PATH,
       'parquet/' || LOWER(T.PRJ_CD) || '/' || LOWER(T.SBJ_AREA_CD) || '/' || LOWER(T.SRC_SCH_NM) || '/' || LOWER(T.SRC_TBL_NM) AS S3_RLT_PATH
  FROM MIG_META.TB_MIG_TBL_MPG T
  JOIN MIG_META.TB_MIG_CONN S ON S.CONN_ID = T.TGT_CONN_ID AND S.ACTIVE_YN = TRUE
  JOIN MIG_META.TB_MIG_SBJ_AREA A ON A.SBJ_AREA_CD = T.SBJ_AREA_CD AND A.ACTIVE_YN = TRUE
 WHERE T.ACTIVE_YN = TRUE;

CREATE VIEW MIG_META.VW_MIG_RUN_SUM AS
SELECT L.RUN_HIST_ID, L.DAG_NM, L.DAG_RUN_ID, L.MPG_ID, L.TASK_NM, L.WRK_DVSN_CD,
       L.LOAD_MTHD_CD, L.WRK_STS_CD, L.SRC_ROW_CNT, L.TGT_ROW_CNT, L.S3_BYTE_SIZE,
       L.S3_MNF_PATH, L.SQL_FILE_PATH, L.SRC_WHERE_CND, L.WRK_STT_DTM, L.WRK_END_DTM,
       L.WRK_ELPS_SEC, L.WRK_MSG, T.PRJ_CD, T.SBJ_AREA_CD, T.SRC_SCH_NM,
       T.SRC_TBL_NM, T.TGT_SCH_NM, T.TGT_TBL_NM
  FROM MIG_META.TB_MIG_RUN_LOG L
  LEFT JOIN MIG_META.TB_MIG_TBL_MPG T ON T.MPG_ID = L.MPG_ID;

CREATE VIEW MIG_META.VW_MIG_DAG_RUN_SUM AS
SELECT D.DAG_EXEC_ID, D.DAG_NM, D.DAG_RUN_ID, D.DAG_DVSN_CD, D.MAP_CNT,
       D.SUC_CNT, D.RUN_CNT, D.ERR_CNT, D.WRK_STS_CD, D.WRK_STT_DTM,
       D.WRK_END_DTM, D.WRK_ELPS_SEC, D.WRK_MSG
  FROM MIG_META.TB_MIG_DAG_RUN D;
