DROP VIEW IF EXISTS MIG_META.VW_MIG_RUN_SUM;
DROP VIEW IF EXISTS MIG_META.VW_MIG_APRV_TBL_MPG;
DROP VIEW IF EXISTS MIG_META.VW_MIG_DAG_TBL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_ARTF_ITEM;
DROP TABLE IF EXISTS MIG_META.TB_MIG_RUN_LOG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_COL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_USR_AUTH;
DROP TABLE IF EXISTS MIG_META.TB_MIG_USR;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_DAG_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_AREA;

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_SBJ_AREA (
    SBJ_AREA_CD VARCHAR(8) NOT NULL,
    SBJ_AREA_NM VARCHAR(200),
    UP_SBJ_AREA_CD VARCHAR(8),
    DISP_ORD INTEGER NOT NULL DEFAULT 0,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_SBJ_DAG_MPG (
    SBJ_AREA_CD VARCHAR(8) NOT NULL,
    DAG_ID VARCHAR(250) NOT NULL,
    DFLT_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    MAX_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_USR_AUTH (
    USR_ID VARCHAR(320) NOT NULL,
    AUTH_ROLE_CD VARCHAR(20) NOT NULL,
    PRJ_CD VARCHAR(100),
    SBJ_AREA_CD VARCHAR(200),
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_USR (
    USR_ID VARCHAR(320) NOT NULL,
    USR_NM VARCHAR(200) NOT NULL,
    PWD_HSH_VAL VARCHAR(1024) NOT NULL,
    PWD_CHG_REQ_YN BOOLEAN NOT NULL DEFAULT TRUE,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_LOGIN_DTM TIMESTAMP,
    PWD_CHG_DTM TIMESTAMP,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_TBL_MPG (
    MPG_ID BIGINT IDENTITY(1,1),
    PRJ_CD VARCHAR(100) NOT NULL,
    SBJ_AREA_CD VARCHAR(200) NOT NULL,
    SRC_CONN_ID VARCHAR(100) NOT NULL DEFAULT 'SRC_GP',
    SRC_SCH_NM VARCHAR(128) NOT NULL,
    SRC_TBL_NM VARCHAR(128) NOT NULL,
    TGT_CONN_ID VARCHAR(100) NOT NULL DEFAULT 'TGT_RED',
    TGT_SCH_NM VARCHAR(128) NOT NULL,
    TGT_TBL_NM VARCHAR(128) NOT NULL,
    TGT_DIST_STYLE VARCHAR(10) NOT NULL DEFAULT 'AUTO',
    TGT_DIST_KEY_COL VARCHAR(128),
    TGT_SORT_STYLE VARCHAR(12) NOT NULL DEFAULT 'AUTO',
    TGT_SORT_COLS VARCHAR(65535),
    TGT_ENCD_AUTO_YN BOOLEAN NOT NULL DEFAULT TRUE,
    LOAD_MTHD_CD VARCHAR(20) NOT NULL DEFAULT 'FULL',
    WM_COL_NM VARCHAR(128),
    INCR_WHERE_TMPL VARCHAR(65535),
    TRNSF_PFL_CD VARCHAR(50) NOT NULL DEFAULT 'S3_PARQUET',
    S3_STG_PATH VARCHAR(1024),
    S3_FILE_FMT_CD VARCHAR(20) NOT NULL DEFAULT 'PARQUET',
    TGT_DDL_SQL VARCHAR(65535),
    DDL_APRV_STS_CD VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    MPG_STS_CD VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    META_VER_NO INTEGER NOT NULL DEFAULT 1,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    APRV_BY VARCHAR(100),
    APRV_DTM TIMESTAMP,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_COL_MPG (
    MPG_ID BIGINT NOT NULL,
    COL_ORD INTEGER NOT NULL,
    SRC_COL_NO INTEGER,
    SRC_COL_NM VARCHAR(128),
    SRC_DATA_TYPE VARCHAR(256),
    SRC_NULL_YN BOOLEAN,
    SRC_KEY_ROLE_CD VARCHAR(20),
    TGT_COL_NO INTEGER,
    TGT_COL_NM VARCHAR(128) NOT NULL,
    TGT_DATA_TYPE VARCHAR(256) NOT NULL,
    TGT_NULL_YN BOOLEAN NOT NULL DEFAULT TRUE,
    TGT_KEY_ROLE_CD VARCHAR(20),
    TRNSF_EXPR VARCHAR(65535),
    DFLT_EXPR VARCHAR(65535),
    SUM_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    HSH_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE OR REPLACE PROCEDURE MIG_META.SP_MIG_COL_MPG_COLNO()
AS $$
DECLARE
    SRC_COL_CNT INTEGER;
    TGT_COL_CNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO SRC_COL_CNT
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'mig_meta'
       AND TABLE_NAME = 'tb_mig_col_mpg'
       AND COLUMN_NAME = 'src_col_no';
    IF SRC_COL_CNT = 0 THEN
        EXECUTE 'ALTER TABLE MIG_META.TB_MIG_COL_MPG ADD COLUMN SRC_COL_NO INTEGER';
    END IF;
    SELECT COUNT(*) INTO TGT_COL_CNT
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'mig_meta'
       AND TABLE_NAME = 'tb_mig_col_mpg'
       AND COLUMN_NAME = 'tgt_col_no';
    IF TGT_COL_CNT = 0 THEN
        EXECUTE 'ALTER TABLE MIG_META.TB_MIG_COL_MPG ADD COLUMN TGT_COL_NO INTEGER';
    END IF;
END;
$$ LANGUAGE plpgsql;

CALL MIG_META.SP_MIG_COL_MPG_COLNO();
DROP PROCEDURE MIG_META.SP_MIG_COL_MPG_COLNO();

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_RUN_LOG (
    RUN_HIST_ID BIGINT IDENTITY(1,1),
    WRK_DT DATE NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    TASK_NM VARCHAR(250),
    MAP_IDX INTEGER,
    EXEC_RUN_ID VARCHAR(250),
    MPG_ID BIGINT,
    META_VER_NO INTEGER,
    SQL_FILE_PATH VARCHAR(1024),
    LOG_FILE_PATH VARCHAR(1024),
    WRK_CND_VAL VARCHAR(65535),
    WRK_STEP_CD VARCHAR(30) NOT NULL,
    WRK_STS_CD VARCHAR(20) NOT NULL,
    WRK_MSG VARCHAR(65535),
    SRC_ROW_CNT BIGINT,
    TGT_ROW_CNT BIGINT,
    SRC_SIZE_BYTE BIGINT,
    TGT_SIZE_BYTE BIGINT,
    WRK_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    WRK_END_DTM TIMESTAMP,
    WRK_ELPS_SEC BIGINT,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_ARTF_ITEM (
    ARTF_CD VARCHAR(20) NOT NULL,
    ITEM_CD VARCHAR(100) NOT NULL,
    ITEM_NM VARCHAR(200) NOT NULL,
    DISP_ORD INTEGER NOT NULL,
    OUT_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE()
);

COMMENT ON SCHEMA MIG_META IS '이관메타데이터';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_AREA IS '이관주제영역';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_NM IS '주제영역명';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.UP_SBJ_AREA_CD IS '상위주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.DISP_ORD IS '표시순서';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_SBJ_DAG_MPG IS '주제영역DAG매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DAG_ID IS 'DAG식별자';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DFLT_PARL_CNT IS '기본병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.MAX_PARL_CNT IS '최대병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_USR_AUTH IS '이관사용자권한';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.USR_ID IS '사용자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.AUTH_ROLE_CD IS '권한역할코드';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.PRJ_CD IS '프로젝트코드';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR_AUTH.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_USR IS '이관사용자';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.USR_ID IS '사용자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.USR_NM IS '사용자명';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.PWD_HSH_VAL IS '비밀번호해시값';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.PWD_CHG_REQ_YN IS '비밀번호변경필요여부';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.LAST_LOGIN_DTM IS '최종로그인일시';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.PWD_CHG_DTM IS '비밀번호변경일시';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_USR.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_TBL_MPG IS '원천대상테이블매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.MPG_ID IS '테이블매핑ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PRJ_CD IS '프로젝트코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SRC_CONN_ID IS '원천접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SRC_SCH_NM IS '원천스키마명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SRC_TBL_NM IS '원천테이블명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_CONN_ID IS '대상접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_SCH_NM IS '대상스키마명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_TBL_NM IS '대상테이블명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_DIST_STYLE IS '대상분산방식';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_DIST_KEY_COL IS '대상분산키컬럼명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_SORT_STYLE IS '대상정렬방식';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_SORT_COLS IS '대상정렬키컬럼목록';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_ENCD_AUTO_YN IS '대상자동압축여부';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.LOAD_MTHD_CD IS '적재방식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.WM_COL_NM IS '증분기준컬럼명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.INCR_WHERE_TMPL IS '증분추출조건템플릿';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TRNSF_PFL_CD IS '이관실행프로파일코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.S3_STG_PATH IS 'S3스테이징경로';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.S3_FILE_FMT_CD IS 'S3파일형식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_DDL_SQL IS '대상DDLSQL';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.DDL_APRV_STS_CD IS 'DDL승인상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.MPG_STS_CD IS '테이블매핑상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.META_VER_NO IS '메타데이터버전번호';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.APRV_BY IS '승인자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.APRV_DTM IS '승인일시';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_COL_MPG IS '원천대상컬럼매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.MPG_ID IS '테이블매핑ID';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.COL_ORD IS '컬럼순서';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SRC_COL_NO IS '원천컬럼순번';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SRC_COL_NM IS '원천컬럼명';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SRC_DATA_TYPE IS '원천데이터타입';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SRC_NULL_YN IS '원천NULL허용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SRC_KEY_ROLE_CD IS '원천키역할코드';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_COL_NO IS '대상컬럼순번';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_COL_NM IS '대상컬럼명';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_DATA_TYPE IS '대상데이터타입';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_NULL_YN IS '대상NULL허용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TGT_KEY_ROLE_CD IS '대상키역할코드';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.TRNSF_EXPR IS '변환SQL식';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.DFLT_EXPR IS '기본값SQL식';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SUM_VALD_YN IS 'SUM검증여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.HSH_VALD_YN IS 'HASH검증여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.UPD_DTM IS '수정일시';

COMMENT ON TABLE MIG_META.TB_MIG_RUN_LOG IS '이관작업이력';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.RUN_HIST_ID IS '작업이력ID';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_DT IS '작업일자';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.DAG_NM IS 'DAG명';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.DAG_RUN_ID IS 'DAG실행ID';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.TASK_NM IS '태스크명';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.MAP_IDX IS '동적태스크순번';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.EXEC_RUN_ID IS '이관실행ID';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.MPG_ID IS '테이블매핑ID';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.META_VER_NO IS '메타데이터버전번호';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.SQL_FILE_PATH IS 'SQL파일경로';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.LOG_FILE_PATH IS '로그파일경로';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_CND_VAL IS '작업조건값';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_STEP_CD IS '작업단계코드';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_STS_CD IS '작업상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_MSG IS '작업메시지';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.SRC_ROW_CNT IS '원천처리건수';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.TGT_ROW_CNT IS '대상처리건수';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.SRC_SIZE_BYTE IS '원천처리크기바이트';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.TGT_SIZE_BYTE IS '대상처리크기바이트';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_STT_DTM IS '작업시작일시';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_END_DTM IS '작업종료일시';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.WRK_ELPS_SEC IS '실행경과초';
COMMENT ON COLUMN MIG_META.TB_MIG_RUN_LOG.CRT_DTM IS '등록일시';

COMMENT ON TABLE MIG_META.TB_MIG_ARTF_ITEM IS '이관산출물항목';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.ARTF_CD IS '산출물코드';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.ITEM_CD IS '산출물항목코드';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.ITEM_NM IS '산출물항목명';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.DISP_ORD IS '출력순서';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.OUT_YN IS '출력여부';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_ARTF_ITEM.UPD_DTM IS '수정일시';

WITH ALPHABET AS (
    SELECT 'A' AS ALPH_CD UNION ALL SELECT 'B' UNION ALL SELECT 'C' UNION ALL SELECT 'D' UNION ALL SELECT 'E' UNION ALL SELECT 'F' UNION ALL SELECT 'G' UNION ALL SELECT 'H' UNION ALL SELECT 'I' UNION ALL SELECT 'J' UNION ALL SELECT 'K' UNION ALL SELECT 'L' UNION ALL SELECT 'M' UNION ALL SELECT 'N' UNION ALL SELECT 'O' UNION ALL SELECT 'P' UNION ALL SELECT 'Q' UNION ALL SELECT 'R' UNION ALL SELECT 'S' UNION ALL SELECT 'T' UNION ALL SELECT 'U' UNION ALL SELECT 'V' UNION ALL SELECT 'W' UNION ALL SELECT 'X' UNION ALL SELECT 'Y' UNION ALL SELECT 'Z'
),
AREA_NO AS (
    SELECT 1 AS AREA_NO UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
),
SBJ_AREA AS (
    SELECT ALPH_CD || '01' AS SBJ_AREA_CD, NULL::VARCHAR(200) AS SBJ_AREA_NM, NULL::VARCHAR(8) AS UP_SBJ_AREA_CD, ASCII(ALPH_CD) - 64 AS DISP_ORD
      FROM ALPHABET
    UNION ALL
    SELECT ALPH_CD || '01' || LPAD(AREA_NO::VARCHAR, 4, '0'), NULL::VARCHAR(200), ALPH_CD || '01', (ASCII(ALPH_CD) - 64) * 100 + AREA_NO
      FROM ALPHABET CROSS JOIN AREA_NO
)
INSERT INTO MIG_META.TB_MIG_SBJ_AREA (SBJ_AREA_CD, SBJ_AREA_NM, UP_SBJ_AREA_CD, DISP_ORD, ACTIVE_YN, CRT_BY, UPD_BY)
SELECT S.SBJ_AREA_CD, S.SBJ_AREA_NM, S.UP_SBJ_AREA_CD, S.DISP_ORD, FALSE, 'MIG_META', 'MIG_META'
  FROM SBJ_AREA S
 WHERE NOT EXISTS (
    SELECT 1
      FROM MIG_META.TB_MIG_SBJ_AREA T
     WHERE T.SBJ_AREA_CD = S.SBJ_AREA_CD
 );

INSERT INTO MIG_META.TB_MIG_SBJ_DAG_MPG (SBJ_AREA_CD, DAG_ID, DFLT_PARL_CNT, MAX_PARL_CNT, CRT_BY, UPD_BY)
SELECT S.SBJ_AREA_CD, 'mig_' || LOWER(S.SBJ_AREA_CD), 1, 1, 'MIG_META', 'MIG_META'
  FROM MIG_META.TB_MIG_SBJ_AREA S
 WHERE S.UP_SBJ_AREA_CD IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
          FROM MIG_META.TB_MIG_SBJ_DAG_MPG D
         WHERE D.SBJ_AREA_CD = S.SBJ_AREA_CD
   );

INSERT INTO MIG_META.TB_MIG_USR (USR_ID, USR_NM, PWD_HSH_VAL, PWD_CHG_REQ_YN, ACTIVE_YN, CRT_BY, UPD_BY)
SELECT 'admin', '초기관리자', 'scrypt$32768$8$1$-ihYMuByxqD894DZdinvpg$QAGOGf-bkxBQnvgQbCxPf7Lnom_FvfoI9lV1a_YjNKk', TRUE, TRUE, 'admin', 'admin'
 WHERE NOT EXISTS (
    SELECT 1
      FROM MIG_META.TB_MIG_USR
     WHERE USR_ID = 'admin'
 );

INSERT INTO MIG_META.TB_MIG_USR_AUTH (USR_ID, AUTH_ROLE_CD, PRJ_CD, SBJ_AREA_CD, ACTIVE_YN, CRT_BY, UPD_BY)
SELECT 'admin', 'ADMIN', NULL, NULL, TRUE, 'admin', 'admin'
 WHERE NOT EXISTS (
    SELECT 1
      FROM MIG_META.TB_MIG_USR_AUTH
     WHERE USR_ID = 'admin'
       AND AUTH_ROLE_CD = 'ADMIN'
       AND PRJ_CD IS NULL
       AND SBJ_AREA_CD IS NULL
       AND ACTIVE_YN = TRUE
 );

UPDATE MIG_META.TB_MIG_SBJ_DAG_MPG
   SET DAG_ID = 'mig_' || LOWER(SBJ_AREA_CD),
       UPD_BY = 'MIG_META',
       UPD_DTM = GETDATE()
 WHERE DAG_ID = 'src_tgt_' || LOWER(SBJ_AREA_CD);

CREATE OR REPLACE VIEW MIG_META.VW_MIG_DAG_TBL_MPG AS
SELECT
    T.MPG_ID,
    T.PRJ_CD,
    T.SBJ_AREA_CD,
    S.SBJ_AREA_NM,
    LOWER(S.SBJ_AREA_CD) AS SQL_DIR_NM,
    D.DAG_ID,
    D.DFLT_PARL_CNT,
    D.MAX_PARL_CNT AS DAG_MAX_PARL_CNT,
    T.SRC_CONN_ID,
    T.SRC_SCH_NM,
    T.SRC_TBL_NM,
    T.TGT_CONN_ID,
    T.TGT_SCH_NM,
    T.TGT_TBL_NM,
    T.LOAD_MTHD_CD,
    T.WM_COL_NM,
    T.INCR_WHERE_TMPL,
    T.TRNSF_PFL_CD,
    T.S3_STG_PATH,
    T.S3_FILE_FMT_CD,
    T.TGT_DDL_SQL,
    T.META_VER_NO
FROM MIG_META.TB_MIG_TBL_MPG AS T
JOIN MIG_META.TB_MIG_SBJ_AREA AS S
  ON S.SBJ_AREA_CD = T.SBJ_AREA_CD
 AND S.ACTIVE_YN = TRUE
JOIN MIG_META.TB_MIG_SBJ_DAG_MPG AS D
  ON D.SBJ_AREA_CD = T.SBJ_AREA_CD
WHERE T.ACTIVE_YN = TRUE;

CREATE OR REPLACE VIEW MIG_META.VW_MIG_APRV_TBL_MPG AS
SELECT
    T.MPG_ID,
    T.PRJ_CD,
    T.SBJ_AREA_CD,
    S.SBJ_AREA_NM,
    LOWER(S.SBJ_AREA_CD) AS SQL_DIR_NM,
    D.DAG_ID,
    D.DFLT_PARL_CNT,
    D.MAX_PARL_CNT AS DAG_MAX_PARL_CNT,
    T.SRC_CONN_ID,
    T.SRC_SCH_NM,
    T.SRC_TBL_NM,
    T.TGT_CONN_ID,
    T.TGT_SCH_NM,
    T.TGT_TBL_NM,
    T.LOAD_MTHD_CD,
    T.WM_COL_NM,
    T.INCR_WHERE_TMPL,
    T.TRNSF_PFL_CD,
    T.S3_STG_PATH,
    T.S3_FILE_FMT_CD,
    T.TGT_DDL_SQL,
    T.META_VER_NO
FROM MIG_META.TB_MIG_TBL_MPG AS T
JOIN MIG_META.TB_MIG_SBJ_AREA AS S
  ON S.SBJ_AREA_CD = T.SBJ_AREA_CD
 AND S.ACTIVE_YN = TRUE
JOIN MIG_META.TB_MIG_SBJ_DAG_MPG AS D
  ON D.SBJ_AREA_CD = T.SBJ_AREA_CD
WHERE T.ACTIVE_YN = TRUE
  AND T.MPG_STS_CD = 'APPROVED'
  AND T.DDL_APRV_STS_CD = 'APPROVED';

CREATE OR REPLACE VIEW MIG_META.VW_MIG_RUN_SUM AS
SELECT
    DAG_NM,
    DAG_RUN_ID,
    MPG_ID,
    META_VER_NO,
    MAX(WRK_STT_DTM) AS LAST_WRK_STT_DTM,
    MAX(WRK_END_DTM) AS LAST_WRK_END_DTM,
    MAX(CASE WHEN WRK_STS_CD = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_YN,
    MAX(CASE WHEN WRK_STS_CD = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_YN,
    MAX(SRC_ROW_CNT) AS SRC_ROW_CNT,
    MAX(TGT_ROW_CNT) AS TGT_ROW_CNT,
    MAX(SRC_SIZE_BYTE) AS SRC_SIZE_BYTE,
    MAX(TGT_SIZE_BYTE) AS TGT_SIZE_BYTE
FROM MIG_META.TB_MIG_RUN_LOG
GROUP BY DAG_NM, DAG_RUN_ID, MPG_ID, META_VER_NO;

COMMENT ON VIEW MIG_META.VW_MIG_APRV_TBL_MPG IS '승인테이블매핑';
COMMENT ON VIEW MIG_META.VW_MIG_DAG_TBL_MPG IS 'DAG실행테이블매핑';
COMMENT ON VIEW MIG_META.VW_MIG_RUN_SUM IS '실행이력요약';
