DROP VIEW IF EXISTS MIG_META.VW_MIG_DAG_RUN_SUM;
DROP VIEW IF EXISTS MIG_META.VW_MIG_RUN_SUM;
DROP VIEW IF EXISTS MIG_META.VW_MIG_DAG_TBL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_ARTF_ITEM;
DROP TABLE IF EXISTS MIG_META.TB_MIG_VALD_COL_RSLT;
DROP TABLE IF EXISTS MIG_META.TB_MIG_VALD_RSLT;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_LOAD_HIST;
DROP TABLE IF EXISTS MIG_META.TB_MIG_S3_MANF;
DROP TABLE IF EXISTS MIG_META.TB_MIG_RUN_LOG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_DEP;
DROP TABLE IF EXISTS MIG_META.TB_MIG_COL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_TBL_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_CONN;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_DAG_MPG;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_DEP;
DROP TABLE IF EXISTS MIG_META.TB_MIG_SBJ_AREA;

CREATE TABLE MIG_META.TB_MIG_SBJ_AREA (
    SBJ_AREA_CD VARCHAR(8) NOT NULL,
    SBJ_AREA_NM VARCHAR(200),
    UP_SBJ_AREA_CD VARCHAR(8),
    DISP_ORD INTEGER NOT NULL DEFAULT 0,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (SBJ_AREA_CD)
);

CREATE TABLE MIG_META.TB_MIG_SBJ_DEP (
    PRE_SBJ_AREA_CD VARCHAR(8) NOT NULL,
    NXT_SBJ_AREA_CD VARCHAR(8) NOT NULL,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (PRE_SBJ_AREA_CD, NXT_SBJ_AREA_CD)
);

CREATE TABLE MIG_META.TB_MIG_SBJ_DAG_MPG (
    SBJ_AREA_CD VARCHAR(8) NOT NULL,
    DAG_DVSN_CD VARCHAR(10) NOT NULL,
    DAG_ID VARCHAR(250) NOT NULL,
    DFLT_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    MAX_PARL_CNT INTEGER NOT NULL DEFAULT 1,
    SCHD_CD VARCHAR(20) NOT NULL DEFAULT 'NONE',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (SBJ_AREA_CD, DAG_DVSN_CD)
);

CREATE TABLE MIG_META.TB_MIG_CONN (
    CONN_ID VARCHAR(100) NOT NULL,
    CONN_NM VARCHAR(200) NOT NULL,
    DBMS_CD VARCHAR(30) NOT NULL,
    CHAR_LEN_MUL SMALLINT NOT NULL DEFAULT 3,
    S3_STG_PATH VARCHAR(1024),
    SEC_SECT_NM VARCHAR(100) NOT NULL,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (CONN_ID)
);

CREATE TABLE MIG_META.TB_MIG_TBL_MPG (
    MPG_ID BIGINT IDENTITY(1,1),
    PRJ_CD VARCHAR(100) NOT NULL,
    SBJ_AREA_CD VARCHAR(8) NOT NULL,
    SRC_CONN_ID VARCHAR(100) NOT NULL,
    SRC_SCH_NM VARCHAR(128) NOT NULL,
    SRC_TBL_NM VARCHAR(128) NOT NULL,
    TGT_CONN_ID VARCHAR(100) NOT NULL,
    TGT_SCH_NM VARCHAR(128) NOT NULL,
    TGT_TBL_NM VARCHAR(128) NOT NULL,
    TGT_DIST_STYLE VARCHAR(12) NOT NULL DEFAULT 'AUTO',
    TGT_DIST_KEY_COL VARCHAR(128),
    TGT_SORT_STYLE VARCHAR(12) NOT NULL DEFAULT 'AUTO',
    TGT_SORT_COLS VARCHAR(65535),
    TGT_ENCD_AUTO_YN BOOLEAN NOT NULL DEFAULT TRUE,
    LOAD_STS_CD VARCHAR(10) NOT NULL DEFAULT 'FULL',
    INCR_BASIS_CD VARCHAR(10),
    INCR_BASIS_COL_NM VARCHAR(128),
    PARL_MTHD_CD VARCHAR(10) NOT NULL DEFAULT 'NONE',
    PARL_CND_ARR VARCHAR(65535),
    TGT_DDL_SQL VARCHAR(65535),
    META_VER_NO INTEGER NOT NULL DEFAULT 1,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MPG_ID)
);

CREATE TABLE MIG_META.TB_MIG_COL_MPG (
    MPG_ID BIGINT NOT NULL,
    COL_ORD INTEGER NOT NULL,
    SRC_COL_NO INTEGER,
    SRC_COL_NM VARCHAR(128),
    SRC_DATA_TYPE VARCHAR(256),
    SRC_NULL_YN BOOLEAN,
    SRC_KEY_ROLE_CD VARCHAR(20),
    TGT_COL_NO INTEGER,
    TGT_COL_NM VARCHAR(128) NOT NULL,
    TGT_DATA_TYPE VARCHAR(256) NOT NULL,
    TGT_NULL_YN BOOLEAN NOT NULL DEFAULT TRUE,
    TGT_KEY_ROLE_CD VARCHAR(20),
    TRNSF_EXPR VARCHAR(65535),
    DFLT_EXPR VARCHAR(65535),
    SUM_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    HSH_VALD_YN BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MPG_ID, COL_ORD)
);

CREATE TABLE MIG_META.TB_MIG_TBL_DEP (
    PRE_MPG_ID BIGINT NOT NULL,
    NXT_MPG_ID BIGINT NOT NULL,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (PRE_MPG_ID, NXT_MPG_ID)
);

CREATE TABLE MIG_META.TB_MIG_RUN_LOG (
    RUN_HIST_ID BIGINT IDENTITY(1,1),
    WRK_DT DATE NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    TASK_NM VARCHAR(250),
    MAP_IDX INTEGER,
    EXEC_RUN_ID VARCHAR(250),
    MPG_ID BIGINT,
    MANF_ID BIGINT,
    META_VER_NO INTEGER,
    S3_MANF_PATH VARCHAR(2048),
    LOAD_MTHD_CD VARCHAR(10),
    INS_SCOPE_CD VARCHAR(20),
    SQL_FILE_PATH VARCHAR(1024),
    LOG_FILE_PATH VARCHAR(1024),
    WRK_CND_VAL VARCHAR(65535),
    WRK_STEP_CD VARCHAR(30) NOT NULL,
    WRK_STS_CD VARCHAR(20) NOT NULL,
    WRK_MSG VARCHAR(65535),
    SRC_ROW_CNT BIGINT,
    TGT_ROW_CNT BIGINT,
    SRC_SIZE_BYTE BIGINT,
    TGT_SIZE_BYTE BIGINT,
    WRK_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    WRK_END_DTM TIMESTAMP,
    WRK_ELPS_SEC BIGINT,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (RUN_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_VALD_RSLT (
    VALD_HIST_ID BIGINT IDENTITY(1,1),
    EXEC_RUN_ID VARCHAR(250) NOT NULL,
    DAG_NM VARCHAR(250) NOT NULL,
    DAG_RUN_ID VARCHAR(250) NOT NULL,
    MPG_ID BIGINT NOT NULL,
    META_VER_NO INTEGER,
    VALD_DVSN_CD VARCHAR(10) NOT NULL,
    S3_MANF_PATH VARCHAR(2048),
    CNT_VALD_STS_CD VARCHAR(20) NOT NULL,
    SRC_CNT BIGINT,
    TGT_CNT BIGINT,
    CNT_DIFF BIGINT,
    SUM_VALD_STS_CD VARCHAR(20) NOT NULL,
    HSH_VALD_STS_CD VARCHAR(20) NOT NULL,
    VALD_STS_CD VARCHAR(20) NOT NULL,
    VALD_STT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    VALD_END_DTM TIMESTAMP,
    VALD_ELPS_SEC BIGINT,
    VALD_MSG VARCHAR(65535),
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (VALD_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_S3_MANF (
    MANF_ID BIGINT IDENTITY(1,1),
    MPG_ID BIGINT NOT NULL,
    EXEC_RUN_ID VARCHAR(250) NOT NULL,
    LOAD_STS_CD VARCHAR(10) NOT NULL,
    INCR_BASIS_CD VARCHAR(10),
    SYS_WRK_DTM TIMESTAMP NOT NULL,
    BASIS_STT_VAL VARCHAR(200),
    BASIS_END_VAL VARCHAR(200),
    S3_MANF_PATH VARCHAR(2048) NOT NULL,
    SRC_S3_VALD_STS_CD VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    TGT_APLY_STS_CD VARCHAR(20) NOT NULL DEFAULT 'READY',
    TGT_APLY_DTM TIMESTAMP,
    S3_TGT_VALD_STS_CD VARCHAR(20),
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MANF_ID)
);

CREATE TABLE MIG_META.TB_MIG_TBL_LOAD_HIST (
    LOAD_TRNS_HIST_ID BIGINT IDENTITY(1,1),
    MPG_ID BIGINT NOT NULL,
    BF_LOAD_STS_CD VARCHAR(10) NOT NULL,
    AF_LOAD_STS_CD VARCHAR(10) NOT NULL,
    BASE_MANF_ID BIGINT,
    TRNS_RSN VARCHAR(1000) NOT NULL,
    TRNS_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (LOAD_TRNS_HIST_ID)
);

CREATE TABLE MIG_META.TB_MIG_VALD_COL_RSLT (
    VALD_HIST_ID BIGINT NOT NULL,
    VALD_ITEM_CD VARCHAR(10) NOT NULL,
    COL_NM VARCHAR(128) NOT NULL,
    SRC_VAL VARCHAR(65535),
    TGT_VAL VARCHAR(65535),
    DIFF_VAL VARCHAR(65535),
    VALD_STS_CD VARCHAR(20) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (VALD_HIST_ID, VALD_ITEM_CD, COL_NM)
);

CREATE TABLE MIG_META.TB_MIG_ARTF_ITEM (
    ARTF_CD VARCHAR(20) NOT NULL,
    ITEM_CD VARCHAR(100) NOT NULL,
    ITEM_NM VARCHAR(200) NOT NULL,
    DISP_ORD INTEGER NOT NULL,
    OUT_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (ARTF_CD, ITEM_CD)
);

COMMENT ON SCHEMA MIG_META IS '이관메타데이터';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_AREA IS '이관주제영역';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_CD IS '주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.SBJ_AREA_NM IS '주제영역명';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.UP_SBJ_AREA_CD IS '상위주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.DISP_ORD IS '표시순서';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_AREA.ACTIVE_YN IS '사용여부';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_DEP IS '주제영역선후행';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DEP.PRE_SBJ_AREA_CD IS '선행주제영역코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DEP.NXT_SBJ_AREA_CD IS '후행주제영역코드';
COMMENT ON TABLE MIG_META.TB_MIG_SBJ_DAG_MPG IS '주제영역DAG관리';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DAG_DVSN_CD IS 'DAG구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.DFLT_PARL_CNT IS '기본병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.MAX_PARL_CNT IS '최대병렬실행건수';
COMMENT ON COLUMN MIG_META.TB_MIG_SBJ_DAG_MPG.SCHD_CD IS '일정코드';
COMMENT ON TABLE MIG_META.TB_MIG_CONN IS '이관접속정보';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_ID IS '접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_NM IS '접속명';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.DBMS_CD IS 'DBMS코드';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CHAR_LEN_MUL IS '문자길이배수';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.S3_STG_PATH IS 'S3스테이징기준경로';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.SEC_SECT_NM IS '비밀설정섹션명';
COMMENT ON TABLE MIG_META.TB_MIG_TBL_MPG IS '원천대상테이블매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.SRC_CONN_ID IS '원천접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_CONN_ID IS '대상접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.LOAD_STS_CD IS '적재상태코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.INCR_BASIS_CD IS '증분기준구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.INCR_BASIS_COL_NM IS '증분기준컬럼명';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PARL_MTHD_CD IS 'S3추출병렬방식코드';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.PARL_CND_ARR IS 'S3추출병렬조건배열';
COMMENT ON COLUMN MIG_META.TB_MIG_TBL_MPG.TGT_DDL_SQL IS '대상DDL문';
COMMENT ON TABLE MIG_META.TB_MIG_COL_MPG IS '원천대상컬럼매핑';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.SUM_VALD_YN IS '합계검증여부';
COMMENT ON COLUMN MIG_META.TB_MIG_COL_MPG.HSH_VALD_YN IS '해시검증여부';
COMMENT ON TABLE MIG_META.TB_MIG_TBL_DEP IS '테이블선후행';
COMMENT ON TABLE MIG_META.TB_MIG_RUN_LOG IS '이관작업이력';
COMMENT ON TABLE MIG_META.TB_MIG_VALD_RSLT IS '이관검증결과';
COMMENT ON TABLE MIG_META.TB_MIG_S3_MANF IS '이관S3매니페스트';
COMMENT ON TABLE MIG_META.TB_MIG_TBL_LOAD_HIST IS '테이블적재상태전환이력';
COMMENT ON TABLE MIG_META.TB_MIG_ARTF_ITEM IS '이관산출물항목';

WITH ALPHABET AS (
    SELECT 'A' AS ALPH_CD UNION ALL SELECT 'B' UNION ALL SELECT 'C' UNION ALL SELECT 'D' UNION ALL SELECT 'E' UNION ALL SELECT 'F' UNION ALL SELECT 'G' UNION ALL SELECT 'H' UNION ALL SELECT 'I' UNION ALL SELECT 'J' UNION ALL SELECT 'K' UNION ALL SELECT 'L' UNION ALL SELECT 'M' UNION ALL SELECT 'N' UNION ALL SELECT 'O' UNION ALL SELECT 'P' UNION ALL SELECT 'Q' UNION ALL SELECT 'R' UNION ALL SELECT 'S' UNION ALL SELECT 'T' UNION ALL SELECT 'U' UNION ALL SELECT 'V' UNION ALL SELECT 'W' UNION ALL SELECT 'X' UNION ALL SELECT 'Y' UNION ALL SELECT 'Z'
), AREA_NO AS (
    SELECT 1 AS AREA_NO UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
), SBJ_AREA AS (
    SELECT ALPH_CD || '01' AS SBJ_AREA_CD, NULL::VARCHAR(200) AS SBJ_AREA_NM, NULL::VARCHAR(8) AS UP_SBJ_AREA_CD, ASCII(ALPH_CD) - 64 AS DISP_ORD FROM ALPHABET
    UNION ALL
    SELECT ALPH_CD || '01' || LPAD(AREA_NO::VARCHAR, 4, '0'), NULL::VARCHAR(200), ALPH_CD || '01', (ASCII(ALPH_CD) - 64) * 100 + AREA_NO FROM ALPHABET CROSS JOIN AREA_NO
)
INSERT INTO MIG_META.TB_MIG_SBJ_AREA (SBJ_AREA_CD, SBJ_AREA_NM, UP_SBJ_AREA_CD, DISP_ORD, ACTIVE_YN)
SELECT SBJ_AREA_CD, SBJ_AREA_NM, UP_SBJ_AREA_CD, DISP_ORD, FALSE FROM SBJ_AREA;

INSERT INTO MIG_META.TB_MIG_SBJ_DAG_MPG (SBJ_AREA_CD, DAG_DVSN_CD, DAG_ID, DFLT_PARL_CNT, MAX_PARL_CNT, SCHD_CD)
SELECT S.SBJ_AREA_CD, D.DAG_DVSN_CD, 'mig_' || LOWER(S.SBJ_AREA_CD) || D.DAG_SFX, 1, 1, 'NONE'
  FROM MIG_META.TB_MIG_SBJ_AREA S
 CROSS JOIN (SELECT 'S3' AS DAG_DVSN_CD, '_s3' AS DAG_SFX UNION ALL SELECT 'INS', '_ins' UNION ALL SELECT 'FULL_CTL', '_full_ctl' UNION ALL SELECT 'INCR_CTL', '_incr_ctl') D
 WHERE S.UP_SBJ_AREA_CD IS NOT NULL;

INSERT INTO MIG_META.TB_MIG_CONN (CONN_ID, CONN_NM, DBMS_CD, CHAR_LEN_MUL, S3_STG_PATH, SEC_SECT_NM, ACTIVE_YN)
VALUES
('SRC_GP', 'Greenplum 원천', 'GREENPLUM', 3, NULL, 'greenplum', TRUE),
('TGT_RED', 'Redshift 대상', 'REDSHIFT', 3, 's3://변경필요', 'redshift_sql', TRUE);

CREATE OR REPLACE VIEW MIG_META.VW_MIG_DAG_TBL_MPG AS
SELECT T.MPG_ID, T.PRJ_CD, T.SBJ_AREA_CD, T.SRC_CONN_ID, T.SRC_SCH_NM, T.SRC_TBL_NM, T.TGT_CONN_ID, T.TGT_SCH_NM, T.TGT_TBL_NM,
       T.LOAD_STS_CD, T.INCR_BASIS_CD, T.INCR_BASIS_COL_NM, T.PARL_MTHD_CD, T.PARL_CND_ARR, T.TGT_DDL_SQL, T.META_VER_NO,
       'parquet/' || LOWER(T.PRJ_CD) || '/' || LOWER(T.SBJ_AREA_CD) || '/' || LOWER(T.SRC_SCH_NM) || '/' || LOWER(T.SRC_TBL_NM) AS S3_RLT_PATH,
       TGT.S3_STG_PATH, SRC.DBMS_CD AS SRC_DBMS_CD, TGT.DBMS_CD AS TGT_DBMS_CD,
       T.SRC_CONN_ID AS SRC_AF_CONN_ID, T.TGT_CONN_ID AS TGT_AF_CONN_ID, 'aws_default' AS S3_AF_CONN_ID
  FROM MIG_META.TB_MIG_TBL_MPG T
  JOIN MIG_META.TB_MIG_SBJ_AREA S ON S.SBJ_AREA_CD = T.SBJ_AREA_CD AND S.ACTIVE_YN = TRUE
  JOIN MIG_META.TB_MIG_CONN SRC ON SRC.CONN_ID = T.SRC_CONN_ID AND SRC.ACTIVE_YN = TRUE
  JOIN MIG_META.TB_MIG_CONN TGT ON TGT.CONN_ID = T.TGT_CONN_ID AND TGT.ACTIVE_YN = TRUE
 WHERE T.ACTIVE_YN = TRUE;

CREATE OR REPLACE VIEW MIG_META.VW_MIG_RUN_SUM AS
SELECT EXEC_RUN_ID, DAG_NM, DAG_RUN_ID, MPG_ID, MAX(META_VER_NO) AS META_VER_NO, MAX(S3_MANF_PATH) AS S3_MANF_PATH, MIN(WRK_STT_DTM) AS WRK_STT_DTM, MAX(WRK_END_DTM) AS WRK_END_DTM, DATEDIFF(second, MIN(WRK_STT_DTM), MAX(COALESCE(WRK_END_DTM, WRK_STT_DTM))) AS WRK_ELPS_SEC, MAX(CASE WHEN WRK_STS_CD = 'FAILED' THEN 1 ELSE 0 END) AS FAIL_YN, MAX(CASE WHEN WRK_STS_CD = 'RUNNING' THEN 1 ELSE 0 END) AS RUN_YN, MAX(SRC_ROW_CNT) AS SRC_ROW_CNT, MAX(TGT_ROW_CNT) AS TGT_ROW_CNT FROM MIG_META.TB_MIG_RUN_LOG GROUP BY EXEC_RUN_ID, DAG_NM, DAG_RUN_ID, MPG_ID;

CREATE OR REPLACE VIEW MIG_META.VW_MIG_DAG_RUN_SUM AS
SELECT EXEC_RUN_ID, DAG_NM, DAG_RUN_ID, COUNT(DISTINCT MPG_ID) AS TBL_CNT, SUM(CASE WHEN WRK_STS_CD = 'SUCCESS' THEN 1 ELSE 0 END) AS SUC_CNT, SUM(CASE WHEN WRK_STS_CD = 'FAILED' THEN 1 ELSE 0 END) AS FAIL_CNT, MIN(WRK_STT_DTM) AS WRK_STT_DTM, MAX(WRK_END_DTM) AS WRK_END_DTM, DATEDIFF(second, MIN(WRK_STT_DTM), MAX(COALESCE(WRK_END_DTM, WRK_STT_DTM))) AS WRK_ELPS_SEC, CASE WHEN SUM(CASE WHEN WRK_STS_CD = 'FAILED' THEN 1 ELSE 0 END) > 0 THEN 'FAILED' WHEN SUM(CASE WHEN WRK_STS_CD = 'RUNNING' THEN 1 ELSE 0 END) > 0 THEN 'RUNNING' ELSE 'SUCCESS' END AS WRK_STS_CD FROM MIG_META.TB_MIG_RUN_LOG GROUP BY EXEC_RUN_ID, DAG_NM, DAG_RUN_ID;
