CREATE TABLE IF NOT EXISTS MIG_META.TB_MIG_CONN (
    CONN_ID VARCHAR(100) NOT NULL,
    CONN_NM VARCHAR(200) NOT NULL,
    CONN_DVSN_CD VARCHAR(10) NOT NULL,
    DBMS_CD VARCHAR(30) NOT NULL,
    SEC_SECT_NM VARCHAR(100) NOT NULL,
    AF_CONN_ID VARCHAR(100) NOT NULL,
    ACTIVE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    CRT_BY VARCHAR(100) NOT NULL,
    CRT_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    UPD_BY VARCHAR(100) NOT NULL,
    UPD_DTM TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (CONN_ID)
);

COMMENT ON TABLE MIG_META.TB_MIG_CONN IS '이관접속정보';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_ID IS '접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_NM IS '접속명';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CONN_DVSN_CD IS '접속구분코드';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.DBMS_CD IS 'DBMS코드';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.SEC_SECT_NM IS 'Secrets섹션명';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.AF_CONN_ID IS 'Airflow접속ID';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.ACTIVE_YN IS '사용여부';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CRT_BY IS '등록자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.CRT_DTM IS '등록일시';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.UPD_BY IS '수정자ID';
COMMENT ON COLUMN MIG_META.TB_MIG_CONN.UPD_DTM IS '수정일시';

INSERT INTO MIG_META.TB_MIG_CONN (CONN_ID, CONN_NM, CONN_DVSN_CD, DBMS_CD, SEC_SECT_NM, AF_CONN_ID, ACTIVE_YN, CRT_BY, UPD_BY)
SELECT 'SRC_GP', 'Greenplum 원천', 'SRC', 'GREENPLUM', 'greenplum', 'SRC_GP', TRUE, 'MIG_META', 'MIG_META'
 WHERE NOT EXISTS (
    SELECT 1
      FROM MIG_META.TB_MIG_CONN
     WHERE CONN_ID = 'SRC_GP'
 );

INSERT INTO MIG_META.TB_MIG_CONN (CONN_ID, CONN_NM, CONN_DVSN_CD, DBMS_CD, SEC_SECT_NM, AF_CONN_ID, ACTIVE_YN, CRT_BY, UPD_BY)
SELECT 'TGT_RED', 'Redshift 대상', 'TGT', 'REDSHIFT', 'redshift_sql', 'TGT_RED', TRUE, 'MIG_META', 'MIG_META'
 WHERE NOT EXISTS (
    SELECT 1
      FROM MIG_META.TB_MIG_CONN
     WHERE CONN_ID = 'TGT_RED'
 );
